### ISSUE TITLE
[BUG]: Cosmos proxy Mixed Content

### ISSUE THREAD

**Issue by vncloudsco** [azukaar/Cosmos-Server#131]
### What happened?

The software does not have the ability to convert all http connections to https, We have tested many software and discovered that the system does not have the feature to switch all connections via https by default, leading to errors.

### What should have happened?

Proxy apps Mixed Content

### Other details

![image](https://github.com/azukaar/Cosmos-Server/assets/41409442/c8129b8b-902f-4c4e-bb3b-51f38264ab53)

### System details

- OS: ubuntu
- Browser  chrome

**Comment by vncloudsco** [comment]
The error was due to my browser, I resolved it successfully

**Comment by saschatrebbin** [comment]
I have exactly this problem and would like to reopen this issue - but as a question.
I want to host firefly III and have Cosmos as the reverse proxy in front of firefly III.

But I get the same error as @vncloudsco:

> Mixed Content: The page at 'https://finanzen.apps.hivenet.xyz/register' was loaded over HTTPS, but requested an insecure stylesheet 'http://finanzen.apps.hivenet.xyz/v3-local/dist/css/adminlte.min.css?v=6.0.30'. This request has been blocked; the content must be served over HTTPS.

This then breaks the webapp, which looks like this:
![ksnip_20231129-221716](https://github.com/azukaar/Cosmos-Server/assets/32403283/3a0e0844-634c-4f36-9648-637f46ab7296)

This happens on several devices and several browsers.
The screenshot is from a fresh flatpak install of Vivaldi.

According to the docs of firefly III [I need to forward the used protocol scheme to the container, so the app responds correctly](https://docs.firefly-iii.org/firefly-iii/faq/installation/#i-get-page-load-errors-because-the-protocols-dont-match).
For nginx the docs provide an example:
`proxy_set_header X-Forwarded-Proto $scheme;`

**My question is: how can I achieve something like that with Cosmos?**
I have taken down the container for now to not expose a half configured webapp to the world.

**Comment by vncloudsco** [comment]
Hello @saschatrebbin I checked the software you are installing and suspected this problem. I found the cause is because this installation did not provide the full environment variables. I created a merge to fix it

**Comment by saschatrebbin** [comment]
That would be this [MR](https://github.com/azukaar/cosmos-servapps-official/pull/110/commits/2cb99b009da793f0dc9cb614da2f89099d3fcd00), correct?

The missing environment variable would then be this line:
`"APP_URL=https://{Hostnames.{StaticServiceName}.{StaticServiceName}.host}",`

I forgot to mention that I do not use the ServApp, but I tested the fix with my docker compose file.
Adding the `APP_URL` environment variable didn't change the behavior of my firefly iii instance.
I also have not seen anything new in the container logs.

According to a comment in the [official .env for firefly-iii](https://raw.githubusercontent.com/firefly-iii/firefly-iii/main/.env.example) file this is environment variable should not help in cases like this.

```
#
# If you have trouble configuring your Firefly III installation, DON'T BOTHER setting this variable.
# It won't work. It doesn't do ANYTHING. Don't believe the lies you read online. I'm not joking.
# This configuration value WILL NOT HELP.
#
# Notable exception to this rule is Synology, which, according to some users, will use APP_URL to rewrite stuff.
#
# This variable is ONLY used in some of the emails Firefly III sends around. Nowhere else.
# So when configuring anything WEB related this variable doesn't do anything. Nothing
#
# If you're stuck I understand you get desperate but look SOMEWHERE ELSE.
#
APP_URL=http://localhost
```

So in my test with a docker compose file the environment variable did exactly what the dev said - absolutely nothing web related.
Can anyone confirm this?

**Comment by vncloudsco** [comment]
@saschatrebbin It's completely normal, please rest assured to use
