### ISSUE TITLE
[FEAT]: One-line install script (like CasaOS)

### ISSUE THREAD

**Issue by petruut** [azukaar/Cosmos-Server#178]
### Feature Description

I think a lot of users sympathise a lot with your vision - I love it!! However, many will like a pre-configured approach (including best practices on how to set up users etc.)

CasaOS is really appealing with its 1-line deployment, that they advertise on their home page. Would something like that be possible to explore here as well?

**Comment by azukaar** [comment]
The one liner is pretty much the docker run command, aside from installing docker itself (another one liner) then you're set

But this  will need to change anyway soon in the future and I do not know  yet how future versions of Cosmos will be delivered

**Comment by petruut** [comment]
I'm grateful - installing docker, managing those initial file/ folder structures, file owners and permissions, installing this container with the right privileges. It's super easy for you, I get that.

But even getting the right PUID and PGID has caused many issues in the past... I think you can't beat the one-liner deployment of CasaOS - you can of course have more advanced users who want this as a layer on top of what they already have. A lot of users I suspect might want something simple - something they can deploy in a VM and have this as the main interface.

**Comment by azukaar** [comment]
You dont need to setup any folder / PID / whatever
- enter terminal
- curl -fsSL https://get.docker.com | sudo sh
- docker run -d -p 80:80 -p 443:443 -p 4242:4242/udp --privileged --name cosmos-server -h cosmos-server --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v /:/mnt/host -v /var/lib/cosmos:/config azukaar/cosmos-server:latest

And you're done. Yes it's 2 commands instead of 1, but it's acceptable I think no?
