### ISSUE TITLE
[FEAT]: Export current containers cosmos-compose to a docke- compose file

### ISSUE THREAD

**Issue by joaofl** [azukaar/Cosmos-Server#25]
### Feature Description

First of all, congrats for the initiative and for the nice development.

I have been strongly looking/testing tools like yours, and so far yours have been the best fit.

My concern now is to not be able to have access to my docker-compose files once they are uploaded and converted into the cosmos-compose format. Do you plan anything like to export all the docker composes back from cosmos compose?

Because if that is not an option, I feel really "no-way-back" situation, which might hold a lots of people back to use it.

**Comment by azukaar** [comment]
> Do you plan anything like to export all the docker composes back from cosmos compose?

Yes I do

>  I feel really "no-way-back" situation

Well not really, because it creates plain containers, which you can actually export to docker-compose again from another tool like Portainer. Cosmos' compose import does not use docker-compose internally so it does not keep the compose file to update stuff further like a docker-compose does. The reason is that, Cosmos follows the pure immutability paradigm of plain plugin-less docker (compose is a plugin) and so it wouldn't make sense to keep those files to edit the stacks. It also is conflicting with the ease of using the UI to manage container to edit files.

My plan is indeed to add an export button to be able to backup setups, reproduce them, etc... In the meantime, you can easily export your setup with something like https://github.com/Red5d/docker-autocompose
At least until it is implemented in Cosmos!

**Comment by joaofl** [comment]
Thanks. That answers it.

**Comment by joaofl** [comment]
Thanks. That answers it.
