### ISSUE TITLE
[BUG]: Docker-compose files does not update when serv-app is updated

### ISSUE THREAD

**Issue by hgpuke** [azukaar/Cosmos-Server#256]
### What happened?

I use Immich as one of the serv-apps. It has undergone several updates since I first installed it. Back then, it was 1.098, now it is 1.105. Regardless, if I go to the container details page and look at the compose-code, it states that it is still running 1.098 which is not true. The web-ui of the app clearly states 1.105.1. 

### What should have happened?

I should have seen version 1.105.1 in the composer file, or :latest

### How to reproduce the bug?

1. Install a serv-app
2. Note down its container version
3. Wait until it updates
4. Note its new container version
5.  Go to the container details page in Cosmos and then to compose-file
6. Look at version number there. Clearly the compose file is not reflecting reality

### Other details

What else is not updated when a serv-app is updated?

### System details

- Debian 11
- Chrome
- Version of Cosmos: 0.15.6

**Comment by azukaar** [comment]
I am assuming that you are updating Immich without updating the container's tag. Because if your image is say Immich:1.2.3 in the compose, then Cosmos will not even update it (because the version is frozen). If your image is Immich:latest, or Immich:1 only then will it be updated by Cosmos.

Otherwise, may be you are referring to some env var not updating properly (as opposed to the image name) to which there's not much I can do. The compose is ALWAYS up to date because it is literally generated dynamically when you navigate to the compose tab based on the container's true state.
