### ISSUE TITLE
[FEAT]: nextcloud aio

### ISSUE THREAD

**Issue by anschein** [azukaar/Cosmos-Server#258]
### Feature Description

Cosmos works very well! I had a little problem, in cosmos servapp there is the basic nextcloud with the backend database and redis, in my use case I need to use nextcloud talk and Collabora Online in conjunction with it, so I installed nextcloud aio in cosmos and everything is almost Everything works fine, except when I use Collabora Online in nextcloud to open a document online, it says Failed to establish socket connection or socket connection closed unexpectedly. The reverse proxy might be misconfigured. proxy might be misconfigured, I'm not sure if it's a problem with the reverse proxy function of urls or if my configuration is wrong, please forgive me for my incompetence in troubleshooting, I have to ask Feat to inquire

https://github.com/nextcloud/all-in-one

**Comment by azukaar** [comment]
- You dont need collabora, the Nextcloud  in the market includes Nextcloud office, which includes Collabora
- for Nextcloud AIO, unfortunately their system does not allow creating a docker-compose for it, you **have** to run their scripts... and it has not been well designed to be proxied, that's why it's a bit of a hassle, but it's possible
- I am not sure what your issue exactly is, but I would start playing around with the security tab of the URL, may be set CORS to *
- I will close this ticket as it is not a Cosmos request
