### ISSUE TITLE
[BUG]: Let's Encrypt rate limit

### ISSUE THREAD

**Issue by l0u1sg** [azukaar/Cosmos-Server#29]
### What happened?

When Cosmos restarts, it asks each time for certificates to be renewed on Let's Encrypt, which means that you quickly reach the Let's Encrypt limit. In my case, when I started transferring infrastructure, I was quickly limited.

### What should have happened?

Cosmos should check the validity of certificates and not renew them, to avoid reaching the limit too quickly and to ensure that the reverse proxy continues to work.

### How to reproduce the bug?

1. Create several urls
2. Restart Cosmos several times

### Relevant log output

```shell
[ERROR] Failed to Init Let's Encrypt. HTTPS wont renew : simplecert: failed to obtain cert: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: [DOMAIN HERE], retry after 2023-06-11T07:51:33Z: see https://letsencrypt.org/docs/duplicate-certificate-limit/, url:
```

### System details

- OS: Ubuntu 
- Browser : Arc (Chromium)
- Version 114.0.5735.106

**Comment by azukaar** [comment]
Hello, it only renews if you have changed the list of URLs, because it needs to get a certif that is valid for whatever new hostname you have added.
You can test this by trying to restart without changing anything and see that it simply picks up a certificate from the cache rather than renewing it.
You can get around this problem by using the DNS Challenge + a wildcard certificate so that Cosmos does not need to renew everytime you add a new subdomain. See doc for details
