### ISSUE TITLE
[FEAT]: Unraid Container?

### ISSUE THREAD

**Issue by Kerbster715** [azukaar/Cosmos-Server#31]
### Feature Description

Hello is there any plan to make this an available container on unraid? or If someone would know to generate the docker-compose file to make it work with unraid. I know 5-10 self-hosters personally that would love to see this on unraid to replace Nginx and Authelia.

**Comment by azukaar** [comment]
Hi!
Sorry, I do not plan on supporting Unraid. 
The issue is that Unraid is a very abrasive, and invasive software. It does not share: for example Unraid will not let anything else edit your containers: if you edit your containers from Cosmos, unraid will revert the changes, which breaks a lot of things.
To support Unraid, a lot of work would be done to basically rewire the UI the "Unraid" way specifically just for Unraid. That would be a nightmare to do and maintain.
I would rather use that energy to work toward Cosmos simply replacing Unraid totally, rather than having them try to work side by side.
