### ISSUE TITLE
[BUG]: URLs: Path Prefix not working (f.e. with Code-Server)

### ISSUE THREAD

**Issue by madejackson** [azukaar/Cosmos-Server#320]
### What happened?

When I try to use a Path Prefix for Code-Server, it doesn't work.
- subdomain no path prefix: works
- subdomain + path prefix: **404: Not Found**
- no subdomain + path prefix: **redirects to /cosmos-ui**

### What should have happened?

Code-Server supports sub-paths via proxy and does not need any config for that, it should just work.
some Sources:
https://github.com/coder/code-server/issues/1987
https://github.com/coder/code-server/issues/241
https://github.com/coder/code-server/discussions/1739

### How to reproduce the bug?

1. Install Code Server
2. go To URLs -> Code Server -> Setup
3. enable "Use Path Prefix", add Path Prefix f.e. /code
4. Save, Test

### Other details

tested with 0.15.7 and 0.16.0-unstable27

### System details

- OS: [e.g. Windows]
- Browser [e.g. firefox]
- Version [e.g. 130.0]

**Comment by azukaar** [comment]
You need the "Strip Path Prefix" to be on, but it seems this option has broken 
I am assuming this happened when I hardened the API routes 2 releases ago
need to take a look

**Comment by madejackson** [comment]
Short Update to this, it's definitely more broken than only strip path prefix. Issue is the same with filebrowser with /filebrowser as subpath configured (so no pathstrip).

- subdomain no path prefix: works
- subdomain + path prefix strip+nostrip: **404: Not Found**
- no subdomain + path prefix strip+nostrip: **redirects to /cosmos-ui**


Also **Custom CORS Origin** seems to be ignored as well. **Disable Header Hardening** disables CORS though no matter the settings in **Custom CORS Origin**.

I can reproduce all of this in 0.15.7 and 0.16.0-beta.

**Comment by azukaar** [comment]
I looked at it, **the issue comes from code-server itself** and generally speaking how path-based routing work (and why I designed Cosmos to highly discourage using this option, such as not having a "path" option in the market).
Long story short, path based routing **works as expected** in Cosmos. I can create  a route to code server that goes to /code-server and shows the app.

The issues you are seeing are:

- If you are NOT enabling "strip-prefix" it is not working because Code-Server does not support "basepath" options. when you go to /code-server , it willl look for that path in the app itself and not find it, and show a 404. **The rule is, any app that does not support basepath explicitly, will not work unless you strip the prefix** (see next point)

- If you DO enable strip prefix, you are essentially hacking the app into believing that request was done to `domain.com` instead of `domain.com/code-server` to force support for base paths. The issue is that you are really accessing /code-server but the app does not know this! In this case, the reason why you see the Cosmos UI when you go to /code-server, is because code-server has a redirection from "/code-server" to "/code-server/" (adding a trailing slash). EXCEPT you hacked code-server into believing it's running with no path (so `domain.com`), so it will redirect you to `domain.com/` instead of `domain.com/code-server/` (and domain.com/ will just show the Cosmos UI). **If you manually go `domain.com/code-server/` instead (with the slash added manualy) then it will suddenly start working!**

This kind of issues is why I just want people to use either ip:port, subdomains, or the newly added .local domains system. Base path DO NOT WORK with most apps, and there's nothing anyone can do about it except the dev of each apps who can add support for it.

![image](https://github.com/user-attachments/assets/10fffa46-749f-434b-a6cf-ea830775c0a5)
