### ISSUE TITLE
[BUG]: Immich compose file depriciated

### ISSUE THREAD

**Issue by Soda47** [azukaar/Cosmos-Server#373]
### What happened?

When trying to install Immich through Cosmos, there are incompabilyties with the new version of the server.
As an exemple, the new app port is 2283 instead of 3001
To change the upload location, it is now defined in the env. instead of volumes
...
The compose file has to be updated to the current format from Immich.
The server is not reachable and not working

### What should have happened?

Server working

### System details

Kubuntu 24.10

**Comment by azukaar** [comment]
Yes this is a general problem with Immich devs changing their minds as often as a teenager about to go to prom. I dont really know what to do about this thought. ANyway We will correct the compose, thanks you or flagging the issue, but please could you report it on the market rather than on cosmos itself? As it is not directly corelated to the software (https://github.com/azukaar/cosmos-servapps-official) thanks

**Comment by Soda47** [comment]
I like your way of explaining it :).
Yes, of course. Thanks for your swift reply.
