### ISSUE TITLE
[HELP]: ServApp isn't serving Jellyfin

### ISSUE THREAD

**Issue by PassiveLemon** [azukaar/Cosmos-Server#41]
### What happened?

Setup a ServApp url for Jellyfin, which works outside of Cosmos. Accessing the url does not show JF.

### What should have happened?

I should be accessing JF

### How to reproduce the bug?

Create ServApp for JF.
CN: /jellyfin
CP: 8096
Proto: http
Target: http://jellyfin:8096

Host: placeholder.mysite.com

### Relevant log output

```shell
Invalid Hostname xx.xxx.xxx.xx for request. Expecting one of [mysite.com placeholder.mysite.com] :
```

### Other details
I have wildcard certificates enabled and have the API keys set (Porkbun)
Same thing happens with my Uptime-Kuma container. I followed the guide here: https://cosmos-cloud.io/doc/5%20URLs/

### System details

- OS: NixOS
- Browser Firefox
- Version 114.0.1

**Comment by azukaar** [comment]
According to the log you redacted you seem  to be trying to use the IP address to access JF you cannot do that anymore with Cosmos you have to use jellyfin.mysite.com (or whatever the domain you have setup)

**Comment by PassiveLemon** [comment]
I have a domain that points to my public ip (Porkbun). I have the root domain and wildcard subdomains point to my ip too.
mysite.com and *.mysite.com.

Would that be the issue?

**Comment by azukaar** [comment]
No that is fine,
What I meant to say is in your message

```
Invalid Hostname xx.xxx.xxx.xx for request. Expecting one of [mysite.com placeholder.mysite.com] :
```

xx.xxx.xxx.xx seems to be an IP no ?

**Comment by PassiveLemon** [comment]
That is my ip but I don't really get what you are saying, sorry. I made the URL in Cosmos and used the link it provided to try to access it

**Comment by azukaar** [comment]
"Invalid Hostname xx.xxx.xxx.xx for request" -- this means you tried to open http://xxx.xxx.xxx.xxx on your browser, which won't work so either
 - You tried to access http://xxx.xxx.xxx.xxx instead of http://jellyfin.domain.com
 - OR you might have a different issue, and that error is unrelated (could be your Tv trying to access Jellyfin via IP because you didnt update the URL for example)

**Comment by PassiveLemon** [comment]
I did try the jellyfin.domain.com as that is what the URL in Cosmos gave me. Just going to expand on my first comment in case that wasn't clear, both the domain.com and *.domain.com point to my xx.xxx.xxx.xx ip address.

I'm not at home right now so I can't show any pictures or share any links but if you need any, let me know and I can send them when I get back.

**Comment by azukaar** [comment]
OK let me know when you're back home, also don't hesitate to ping me on Discord directly, so you can share more details in private :)

**Comment by azukaar** [comment]
@PassiveLemon I found the issue! It's because HTTPS wasn't setup during the first install (or at least not working, aka. no certificates were presents) so Cosmos started the HTTP server instead, and then when you edited the settings it was not able to hot reload between the two different servers (did not implement that edge case). That's why the restart fixed it.
I will implement hot reloading between the two different servers today and nobody will see that issue again!
