### ISSUE TITLE
[FEAT]: Show Modal Update available

### ISSUE THREAD

**Issue by Serph91P** [azukaar/Cosmos-Server#67]
### Feature Description

Would be great if you could do a Modal of some sorts which shows that an update is available. Maybe I didnt see it like the update button. So in respect of viability it would be great to have somthing like a Update tab or a Big red Flashing Button like Uppdate :D

**Comment by azukaar** [comment]
When an update is available but auto-update is off, the update button will shines. I know this is super obvious, but the reason why I didn't bother doing more than this, is because later on I will implement a complete notification system (on errors, or container crash, etc...) which will include getting notifications when updates are available
